<a href="https://colab.research.google.com/github/ncwalker59/hello-world/blob/main/FINALCAPSTONEPROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd                     
import matplotlib.pyplot as plt          # plotting
import numpy as np                       # dense matrices
from scipy.sparse import csr_matrix      # sparse matrices
%matplotlib inline

from google.colab import drive

# see whole dataset
pd.set_option('display.max_rows', 500)

drive.mount('/content/gdrive')
df = pd.read_csv('/content/gdrive/My Drive/Colab Datasets/WorldCupPKs.csv')

#raw data table
print(df)

# bar graph of all PKs on target 
import plotly.express as px
df = pd.read_csv('/content/gdrive/My Drive/Colab Datasets/WorldCupPKs.csv')
fig = px.bar(df, x='Foot', y='OnTarget', color='Zone_Simple')
fig.show()

#chi-squared tests
from scipy.stats import chi2_contingency
from scipy.stats import chi2

# chi-squared test for PKs on target
table = [	[19, 12, 21],
			[96,  38,  70]]
print(table)
stat, p, dof, expected = chi2_contingency(table)
print('dof=%d' % dof)
print(expected)
# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
 
# chi-squared test for elimination PKs on target
table = [	[1, 3, 3],
			[12,  3,  10]]
print(table)
stat, p, dof, expected = chi2_contingency(table)
print('dof=%d' % dof)
print(expected)
# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
print('*tables indicate observed values*\n')

#Research Findings
print('Concusion: Right-footed kickers appear to prefer the left side of goal, while left-footed kickers tend to prefer the right side \n a p-value > 0.05 indicates this correlation could be attributed to randomness, but the findings were stronger in elimination situations')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
     Zone Foot Keeper  OnTarget  Goal  Elimination Zone_Simple
0       7    R      R         1     1            0           L
1       9    R      C         1     1            0           R
2       6    R      L         1     1            0           R
3       2    R      C         1     1            0           C
4       9    R      L         1     1            0           R
5       4    R      L         1     0            0           L
6       8    L      L         1     0            0           C
7       3    R      R         1     1            0           R
8       9    R      L         1     1            0           R
9       9    R      C         1     1            1           R
10      7    R      L         1     0            0           L
11      9    R      C         1     1            1           R
12      4    R      L         1     0            0

[[19, 12, 21], [96, 38, 70]]
dof=2
[[23.359375 10.15625  18.484375]
 [91.640625 39.84375  72.515625]]
probability=0.950, critical=5.991, stat=1.871
Independent (fail to reject H0)
significance=0.050, p=0.392
Independent (fail to reject H0)
[[1, 3, 3], [12, 3, 10]]
dof=2
[[ 2.84375  1.3125   2.84375]
 [10.15625  4.6875  10.15625]]
probability=0.950, critical=5.991, stat=4.318
Independent (fail to reject H0)
significance=0.050, p=0.115
Independent (fail to reject H0)
*tables indicate observed values*

Concusion: Right-footed kickers appear to prefer the left side of goal, while left-footed kickers tend to prefer the right side 
 a p-value > 0.05 indicates this correlation could be attributed to randomness, but the findings were stronger in elimination situations
